name: Bug report
description: Report something that isn't working
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: "Short description of the bug"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How can we reproduce it?
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs or attach screenshots if helpful.
      render: shell
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS / runtime / version info
      placeholder: "macOS 14, Node 20, etc."

